deprecated submit_to_isis

diff --git a/bin/submit_to_isis b/bin/submit_to_isis
--- a/bin/submit_to_isis
+++ b/bin/submit_to_isis
@@ -9,12 +9,12 @@
 # Note that you should apply quotation marks (") around a complex command!
 
 echo "##################################################################"
-echo "WARNING! This function is about to be retired. Please learn to use"
+echo "ERROR! This function has been retired. Please learn to use"
 echo "  stormdb-python/bin/submit_to_cluster"
 echo "instead (see submit_to_cluster --help for usage)."
-echo "This function will continue in 5 seconds (hit Ctrl-C to quit.)"
 echo "##################################################################"
-sleep 5
+
+exit 1
 
 NTHREADS=$1
 EXEC_CMD=${@:2}
